name: Deploy AOTW

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    name: Deploy Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: task_set_aotw
          region: us-west1
          runtime: python310
          source_dir: .
          entry_point: task_set_aotw
          project_id: ${{ secrets.PROJECT_ID }} 
