name: Deploy AOTW

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Function
    runs-on: ubuntu-latest

    permissions: # Recommended, but not strictly required for this specific error
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug Secret (REMOVE THIS AFTER DEBUGGING!)
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: Project Secret (REMOVE THIS AFTER DEBUGGING!)
        run: echo "${{ secrets.PROJECT_ID }}"

      - name: Authenticate Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Deploy Function - AOTW Email
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: AOTW
          region: us-west1
          runtime: python310
          source_dir: .
          entry_point: task_daily_email
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Deploy Function - AOTW Trigger
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: Search-AOTW
          region: us-west1
          runtime: python310
          source_dir: .
          entry_point: task_set_aotw
          project_id: ${{ secrets.PROJECT_ID }}

      - name: (Test) Deploy Function - AOTW Email
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: Test-AOTW-daily-email
          region: us-west1
          runtime: python310
          source_dir: .
          entry_point: task_dev_daily_email
          project_id: ${{ secrets.PROJECT_ID }}

      - name: (Test) Deploy Function - AOTW Trigger
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: Test-set-AOTW
          region: us-west1
          runtime: python310
          source_dir: .
          entry_point: task_dev_set_aotw
          project_id: ${{ secrets.PROJECT_ID }}
